[package]
name = "rnewscraper"
version = "0.0.1"
authors = ["davidedelpapa <davidedelpapa@yahoo.com>"]
edition = "2018"

[dependencies]
reqwest = "0.10.0"
scraper = "0.11.0"
tokio = { version = "0.2", features = ["macros"] }
